apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi  #i created 20gb storage in aws already so to match that i gave 20gb 
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-09035152cf09c4b1c
 