kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-expense
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-09df0637e7bc78de9  #file system wont create automatically only the mount points create automatically 
  directoryPerms: "700" 
  basePath: "/expense" 