apiVersion: v1
kind: Pod 
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    env: 
    - name: course
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: course #env.name and configmap key name can be different 
    - name: trainer
      value: "siva" 
    - name: duration
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: duration 
