apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx 
  labels:    #replica set labels
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:  #these are used to select the pod to create replicas
      tier: frontend
      app: nginx
  template:   #this is pod template
    metadata:
      labels:  #these labels belongs to pod 
        tier: frontend
        app: nginx 
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl 
---
kind: Service
apiVersion: v1
metadata:
 name: nginx
spec: 
  selector:
    tier: frontend
    app: nginx 
  ports:
    - name: nginx-service-port
      protocol: TCP
      port: 80  #service port
      targetPort: 80 #container port 
